### ISSUE TITLE
Feat: Reviews and Rating for the Service used

### ISSUE THREAD

**Issue by nkthis** [BookMySport-com-Platform/User-Slot-Booking#14]
In this feature user who has booked the slot and completed the time frame which is allotted to him/her 
Then he will be eligible to review and rate the service provided by the service provider and eligible service provider can view that specific rating that has been given to him/her.

**Comment by anandateertha-dev** [comment]
> In this feature user who has booked the slot and completed the time frame which is allotted to him/her Then he will be eligible to review and rate the service provided by the service provider and eligible service provider can view that specific rating that has been given to him/her.

Do mean giving start to the particular sport?

**Comment by nkthis** [comment]
Review and Rating for a particular service provider when anyone uses the playground at the allotted time frame !!

**Comment by anandateertha-dev** [comment]
> Review and Rating for a particular service provider when anyone uses the playground at the allotted time frame !!

We can also ask for the stars for the sport they have played as well as for the overall playground, right??

**Comment by nkthis** [comment]
Yes

**Comment by anandateertha-dev** [comment]
@nkthis I think this feature will be implemented in the other 2 repositories.

Service provider rating: Authentication service
sport rating: Service provider place registration repository

**Comment by nkthis** [comment]
we have to do analysis on that because it might be possible that all 3 repositories are included in this ..

**Comment by anandateertha-dev** [comment]
I didn't get your point!

**Comment by anandateertha-dev** [comment]
> we have to do analysis on that because it might be possible that all 3 repositories are included in this ..

This repository is for all the activities done by the user like,
1. Booking the slot
2. Resheduling the slot
3. Cancelling the slot

**Comment by nkthis** [comment]
after the booking the slot at the particular time frame after the booking time is over user should be able to see the rating process!
but it will not be shown before the booking time that means if slot is booked between 7-8 PM then user should be able to see rating process after 8 P.M only !!

**Comment by anandateertha-dev** [comment]
> after the booking the slot at the particular time frame after the booking time is over user should be able to see the rating process! but it will not be shown before the booking time that means if slot is booked between 7-8 PM then user should be able to see rating process after 8 P.M only !!

Yeah! We can handle this in front-end very easily!

**Comment by nkthis** [comment]
Okay no need of backend in this ?

**Comment by anandateertha-dev** [comment]
> Okay no need of backend in this ?

To store and analyze the rating we need to write the logic in Authentication service and service provider reg repo.

**Comment by nkthis** [comment]
okay
