### ISSUE TITLE
Bug: The price is displayed as zero in the database when user books a slot.

### ISSUE THREAD

**Issue by anandateertha-dev** [BookMySport-com-Platform/User-Slot-Booking#4]
> Description on the bug:

When the user books a slot through the end-point /api/bookslot, the slot is being booked but the price is not calculated. I have written the middleware to get the price details from Service-Provider-Place-Registration service and multiplied the price with the number of hours the user has booked the court.

> total hours = stopTime - startTime
> price = ( price-per-hour-per-sport * total hours)
> 

The issue here is the price is displayed as zero instead of total amount. 

To get the price I have interacted with this repository with api end-point as api/getsportbyspidandsportid

https://github.com/BookMySport-com-Platform/Service-Provider-Place-Registration/blob/main/src/main/java/com/bookmysport/service_provider_place_reg/Controllers/SPMainController.java

I have designed a middleware to get the information of price from Service-Provider-Place-Registration service. Check that out from below link.

https://github.com/BookMySport-com-Platform/User-Slot-Booking/blob/main/src/main/java/com/bookmysport/userslotbooking/MiddleWares/GetSportBySportIDAndSpid.java

Image of Database: 
![image](https://github.com/BookMySport-com-Platform/User-Slot-Booking/assets/154119282/d3dc0a53-bdfe-495b-a77b-f2b27b522804)

> Code for Middleware: 

```
package com.bookmysport.userslotbooking.MiddleWares;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import com.bookmysport.userslotbooking.Models.ResponseMessage;

import reactor.core.publisher.Mono;

@Service
public class GetSportBySportIDAndSpid {
    @Autowired
    private WebClient webClient;

    @Value("${GETSPORTBYSPORTIDANDSPID_URL}")
    String getsportbyspidandsportidURL;

    @Autowired
    private ResponseMessage responseMessage;

    public int getSportAndSpDetailsService(String token, String role, String sportId) {
        try {
            Mono<Map<String, Object>> sportAndSpDetailsMono = webClient.get()
                    .uri(getsportbyspidandsportidURL)
                    .headers(headers -> {
                        headers.set("Content-Type", "application/json");
                        headers.set("token", token);
                        headers.set("role", role);
                        headers.set("sportId", sportId);
                    })
                    .retrieve()
                    .bodyToMono(new ParameterizedTypeReference<Map<String, Object>>() {
                    });
            Map<String, Object> sportAndSpDetails = sportAndSpDetailsMono.block();
            System.out.println("This");
            System.out.println(sportAndSpDetails);
            if (sportAndSpDetails != null) {
                    System.out.println("Inside middleware");
                    System.out.println(sportAndSpDetails.get("pricePerHour"));
                    return (Integer)sportAndSpDetails.get("pricePerHour");
            } else {
                responseMessage.setSuccess(false);
                responseMessage.setMessage("No Sport exists with this spId or SportId");
                return 0;
            }
        } catch (Exception e) {
            responseMessage.setSuccess(false);
            responseMessage.setMessage("Internal Server Error in GetSportBySportIDAndSpid. Method: getSportAndSpDetailsService. Error message: " + e.getMessage());
            return 0;
        }
    }
}
```

**Comment by anandateertha-dev** [comment]
Guys I made an seperate end-point for getting the price, I am getting the price-per-hour for the particular sport. But I am not getting while booking the slot.

![image](https://github.com/BookMySport-com-Platform/User-Slot-Booking/assets/154119282/72907951-c07f-487b-8481-29c8faf9a911)

**Comment by nkthis** [comment]
Ok it's good !! separate endpoint can be used to fetch the price 
you have the modify the existing code !

**Comment by anandateertha-dev** [comment]
If we do that we have more API calls than usual.

**Comment by nkthis** [comment]
yeah will check your code today in my system and will debug the same 
 and then will see what is the issue with your code !!
